# The URL the site will be built for
base_url = "https://limboy.me"

title = "Limboy"

default_language = "zh"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

feed_filename = "index.xml"

generate_feed = true

taxonomies = [{ name = "tags", feed = true }, { name = "subject", feed = true }]

ignored_content = []

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "demain"

[extra]
# Put all your custom variables here
[extra.giscus]
[extra.giscus.telescope]
repo = 'telescope'
repo_id = 'MDEwOlJlcG9zaXRvcnkzODEwOTA2MTg='
category = 'General'
category_id = 'MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMzMDY2MTQy'
[extra.giscus.limboy]
repo = 'limboy.me'
repo_id = 'R_kgDOGqD9cw'
category = 'General'
category_id = 'DIC_kwDOGqD9c84CAoVe'
